### PR TITLE
Calculator assignment

### PR DESCRIPTION
**Pull request by sahil97**
please review and suggest any changes.

### CODE REVIEW

**Comment by shivamras304** [comment]
Good job on the styling. Now please add the required functionality of the calculator via JS. I am not closing your PR. Your next commits will be added to this PR.

**Comment by sahil97** [comment]
I've added js and updated the netlify link in readme.md .
Kindly see and review.

**Comment by sahil97** [comment]
I request you to please review it a little soon as I have to push the weekly project as well.

**Comment by sahil97** [comment]
The commits contains both netlify links for calc and week-1 project.
Please check and review

**Comment by shivamras304** [comment]
Hi Sahil

I've reviewed both your calculator app and week 1 project. I am a fan of minimal UI and I guess you are too.
Good job on keeping the calculator minimal and functional via JS
Really liked your use of PaperCSS framework on the week1 project. I see you tried using firebase also. It doesn't work for me. You can look into it.

Overall, good job for both the projects :+1:

**Comment by sahil97** [comment]
Thanks for the review.I tried using firebase, but was told that it would be done using C#, so I did not correct that code later. My main problem with firebase is of using it from scratch as there is no good tutorial of it online. I'll still search though. If you have any good links, please share.

**Comment by shivamras304** [comment]
I'm confident that you can integrate it with firebase without any tutorial.
Just refer the good ol' documentation.
(On your own time, this isn't a requirement)

**Pull request merged**
