### PR TITLE
week 1 project 

### PR DESCRIPTION
**Pull request by sh9re5ya97**
week 1 project for review
(without JS)

### CODE REVIEW

**Comment by sh9re5ya97** [comment]
netlify link:
https://heuristic-hugle-aa4758.netlify.com/

**Comment by sh9re5ya97** [comment]
in the list there is one demo link for retrieve ( on the first name: nick fury)

**Comment by sh9re5ya97** [comment]
JS for calculator added
netlify:
https://happy-goldstine-0252e5.netlify.com/

**Comment by shivamras304** [comment]
Marvel fan, are we?
Good job Shreya!

**Comment by sh9re5ya97** [comment]
haha, yes!
Thankyou!

**Comment by sh9re5ya97** [comment]
haha, yes!
Thankyou!

**Pull request merged**
