### PR TITLE
weak-1

### PR DESCRIPTION
**Pull request by DeepakBansal1996**
sorry for late

netlify link

https://keen-dubinsky-2b166c.netlify.com

### CODE REVIEW

**Comment by DeepakBansal1996** [comment]
it include my week1(User Interface) and week2(CRUD operations from database) task 
note. (When you want to DELETE records from Employee table, first you need delete record from database in Designation and Department Table because they have relation with Employee Table    )

**Comment by shivamras304** [comment]
Hi Deepak
Merged your code. You should work on your CSS skills. There's unwanted padding and margin that you could have easily removed at the beginning using:
`* {`
`margin: 0;`
`padding: 0;`
`}`

**Comment by DeepakBansal1996** [comment]
Thank you shivam
  i will defenetly work on my CSS skills

**Comment by DeepakBansal1996** [comment]
Thank you shivam
I will defenetly work on my CSS skills

**Pull request merged**
