### PR TITLE
Week-1 project 

### PR DESCRIPTION
**Pull request by srishty12rawat**

### CODE REVIEW

**Comment by shivamras304** [comment]
Hi Srishty
I have gone through your code and good job on the quick submission 👍. However, I won't be able to merge your code right now and will get back to you if your work needs any changes.
Also, please submit your calculator code if you haven't :)

**Comment by srishty12rawat** [comment]
pages are responsive now

**Comment by srishty12rawat** [comment]
Hey shivam,
For my Week-1 project, you can directly view it though this link. 
https://srishty03.netlify.com/

**Comment by srishty12rawat** [comment]
https://srishty02.netlify.com/
Through this, you can check my calculator too.

**Comment by srishty12rawat** [comment]
Hey Shivam,
I've already submitted my PRs for both of the projects. 
I've also provided the netlify links for the same.
Thanks,
Srishty ( INT 027 )

**Comment by shivamras304** [comment]
Hi Srishty

I have reviewed both your calculator project and week1 project.
There's a design feature I really liked in your calculator and when I looked at the code I, I think it is a bug and not something you intended to do. Nevertheless, I got an interesting design idea. Thanks!

For, the Week 1 project, yes you met all the requirements. But I wish you had put in more effort in some of the pages like list-page. Also, there is an issue with how you navigate all your pages. I couldn't reach all the pages from the netlify link and I found out that you had created all the pages when I looked at your repo. I'll quote from the email I sent:
>You all must have created several HTML files for different pages (Sign up, List all users etc)
>Now create an index.html file which contains links to all those files using anchor tag.

Good job at your first project! You do have the potential to do better :)

**Pull request merged**
